### ISSUE TITLE
Grüvee website brainstorm / planning

### ISSUE THREAD

**Issue by edburtnieks** [PixelogicDev/Gruvee-Mobile#147]
The plan is to release version 1.0 of Grüvee at the end of this year. There has been already some mentioning and thought about making a website / landing page for Grüvee under `https://gruvee.pixelogic.dev/` domain.
So maybe this issue can be a start of planning it and getting ideas out.

## Todo

* [ ] Plan and collect ideas and thoughts on
  * [ ] Infrastructure
  * [ ] Content
  * [ ] Additional features if any
  * [ ] ...
* [ ] Show ideas and thoughts in an organized way

**Comment by adilanchian** [comment]
Thanks for starting this, @edburtnieks ! So I am a fan of simple and to the point, landing pages for apps. For example:

https://getcyclesapp.com/

I think it's a pretty simple page that gets the point across! I think it could be SUPER cool to create a template that we use for all the apps part of PixelogicDev. Thoughts?
