### ISSUE TITLE
[Release-1.0] Create Social auth flow

### ISSUE THREAD

**Issue by adilanchian** [PixelogicDev/Gruvee-Mobile#15]
We would like to be able to auth with multiple social platforms. I believe this should be setup similar to our serverless approach, but not entirely sure yet.

### Tasks
- Generate UI for both Android & iOS (Push up Sketch file)
- Setup auth for each platform (Will probably need some sort base component that can be reused with multiple platforms)
- Setup own account creation layer 

### Platforms
Both platforms:
- SoundCloud
- ~Spotify~
- iCloud
- Google

This list could change, but let's make a generic social auth flow here.

**Comment by adilanchian** [comment]
Currently working on the Spotify auth and almost done with it! 
### What We Did Today
- Merged a brand new file structure into `release-1.0`

### What We Will Do Tomorrow
- [ ] Improve tooling for React Native
- [ ] Update README as necessary
- [ ] Will need to move to backend repo to add in create user firebase function

**Comment by adilanchian** [comment]
### What We Did Today 
- Added new extensions for React Native Project
- Improved overall tooling
- Realized we need to update the README (Will do offline as first draft)
- Started working on CreateUser Firebase Function in Golang

### What We Will Do Tomorrow
- [ ] Continue working on CreateUser Firebase Function
- [ ] Refactor the Spotify Auth on client to utilize new Firebase function

**Comment by adilanchian** [comment]
### What We Did Today
- Figured out more about local develop with Golang and Firebase functions
- Added CreateSocialPlatform function and it works!
- Continued editing the CreateFirebaseUser function

### What We Will Do Tomorrow
- [ ] Continue writing CreateFirebaseUser function
- [ ] Setup local flag for Golang (ie for replace & pointing locally or to prod)

**Comment by adilanchian** [comment]
### What We Did Today
- Finished up the createuser function
- Finished up the socialplatform function
- Returned our payload to client (HYPE Y33333T)

### What We Will Do Tomorrow
- [ ] Setup local flag for Golang (ie for replace & pointing locally or to prod)
- [ ] Do cleanup for Golang functions (error handling and such)
- [ ] Reconfigure our client to handle new changes from service

**Comment by adilanchian** [comment]
### What We Did Today
- Finished Spotify Auth!
- Logged some bugs!
- Did THE THINGS

### What We Will Do Tomorrow
- [ ] Create refreshToken Firebase Function
- [ ] Move onto another Auth Flow

**Comment by adilanchian** [comment]
### What We Did Today
- Finished writing the main checking logic for refreshToken function
- Added new payload data to client

### What We Will Do Tomorrow
- [ ] Add proper endpoints for actually refreshing token and then writing to DB
- [ ] Add env variables to Golang
- [ ] Merge `master` to get the latest package updates

**Comment by adilanchian** [comment]
### What We Did Today
- We wrote our retrospective for the last 100 days of Grüvee development (expect a article on this #soon)
- We added some new Golang env stuff (YAML YAYA)
- We finished up our token refresh firebase function

### What We Will Do Tomorrow
- [ ] We need to change the endpoints in Golang based on env variable
- [ ] MERGE all this this master
- [ ] Add TokenRefresh call where ever we feel we need it

**Comment by adilanchian** [comment]
### What We Did Today
- Merged all of the Golang changes to `master`
- Ran into a Golang versioning problem 
- Started working on how to fix this versioning problem and found a solution!

### What We Will Do Tomorrow
- [ ] Fix up Golang version issue (ie tag each module with it's own version and include `.version` file)
- [ ] Do a Firebase functions test deployment to make sure things work
- [ ] Return to client for sign in bug & more auth

**Comment by adilanchian** [comment]
We are going to move on from auth for now, but will keep this issue open for when we return to a new platform

**Comment by adilanchian** [comment]
I am going to close this to make separate issues for each one
